import React, { Component } from 'react';
import css from 'styled-components';
import { FormattedMessage as Msg } from 'gatsby-plugin-intl';

import SEO from '../../../../components/Seo';
const Wrap = css.div`
  padding: 16px;
`;

const Paragraph = css.p`
  font-size: 12px;
  line-height: 1.5em;
  color: #282828;
  margin-bottom: 20px;
  text-align: justify;
`;

export default class Agreement extends Component {
  
  render() {
    const lang = 'zh';
    const agreement = {
      zh: [
        '尊敬的用户：',
        '感谢您选择Bycoin服务。《Bycoin服务协议》（以下简称“本协议”）由Hangzhou Super Node Information Technology Co. Lt.（以下简称“Super Node”或“我们”）和用户（以下简称“您”或“用户”）签订，本协议在您与Super Node之间具有合同上的法律效力。',
        'Super Node在此特别提醒您在使用Bycoin（以下简称“Bycoin” 或“本软件”）之前，请认真阅读《Bycoin服务协议》及后文提到的相关协议，尤其是本协议规定的“免责及责任限制”等条款将以加粗的形式体现，确保您充分理解本协议中各条款，并自主考虑风险。',
        '一、 关于本协议的确认与接纳',
        '1. 您理解本协议及有关协议适用于Bycoin相关服务。',
        '2. 您下载Bycoin软件并创建或导入钱包，即视为您已经充分阅读并接受本协议全部条款，本协议立即生效，对双方具有约束力。',
        '3. 本协议可由Super Node随时更新，经修改的协议一经在Bycoin上公布，立即自动生效，恕不再另行通知。在Super Node公布修改协议条款后，如果您不接受修改后的条款，请立即停止使用Bycoin，您继续使用Bycoin将被视为接受修改后的协议。',
        '4. 如果您未满18周岁，或者是无民事行为能力人或限制民事行为能力人，请在父母或监护人指导下使用Bycoin。',
        '二、 定义',
        '1. Bycoin：指由Super Node基于Bytom（及将来陆续支持的其他公链）开发的区块链钱包，包括其他为方便用户使用区块链系统而开发的辅助工具。',
        '2. 用户：',
        '（1）用户必须是具备完全民事行为能力的自然人；',
        '（2）若您为18周岁以下的未成年人使用Bycoin服务，需要在您父母或监护人的指导下使用Bycoin。无民事行为能力人使用Bycoin或限制民事行为能力人超过其民事权利或行为能力范围从事交易的，造成的一切后果，Bycoin有权要求您及您的父母或监护人负责。',
        '3. 创建或导入钱包：指您使用Bycoin，确认履行本协议并创建或导入钱包的过程。',
        '4. 钱包密码：指您在创建Bycoin钱包过程中，软件操作界面提示您填写的密码，该密码用于加密保护私钥。作为去中心化的应用，钱包密码不存储在您的这台移动设备或Super Node的服务器，一旦丢失你需要借助明文私钥或助记词重置新密码。',
        '5. 信息提示：Bycoin软件操作界面涉及的信息提示内容，建议用户按照相关步骤进行操作。',
        '6. 特定用户：指按照中国法律法规及政策规定必须要配合Super Node履行个人信息披露义务的用户。',
        '7. 私钥：由256位随机字符构成，是用户拥有并使用数字资产的核心。',
        '8. 公钥：由私钥借助密码学原理单向推导生成，并用以生成区块链数字钱包地址，数字钱包地址即为公开收款地址。',
        '9. 助记词：符合区块链BIP39 行业标准，由随机算法生成的12（或15/18/21/24）个有序单词组成。是私钥的易记录表现形式，方便用户备份保管。',
        '10. Keystore: 是私钥或助记词经过用户设置的钱包密码加密保存的文件形式，它只存储在您的这台移动设备中，不会同步至Super Node服务器。',
        '11. 数字资产：指Bycoin目前支持的数字资产种类，包括但不限于BTM等。',
        '12. 个人信息：指以电子或者其他方式记录的能够单独或者与其他信息结合识别用户个人身份的各种信息，包括但不限于自然人的姓名、出生日期、身份证件号码、个人生物识别信息、住址、电话号码、银行卡号、邮件地址、钱包地址、移动设备信息、操作记录、交易记录等，但不包括用户的钱包密码、私钥、助记词、Keystore。',
        '三、 服务内容',
        '1. 创建或导入钱包。对Bycoin支持的数字资产，您可以使用Bycoin生成新钱包或导入相关区块链系统的其它钱包工具生成的兼容钱包。',
        '2. 转账、收款。您可以使用Bycoin的转账、收款功能进行数字资产的管理，即运用私钥进行电子签名，对相关区块链的账本进行修改。转账是指付款方利用收款方的区块链地址进行转账操作，实际的转账、收款行为均在相关区块链系统（而非Bycoin）发生。',
        '3. 管理数字资产。您可以使用Bycoin添加、保管并移除Bycoin所支持的数字资产（BTM除外）。',
        '4. 交易记录。我们将通过区块链系统拷贝您全部或部分的交易记录。但交易记录以区块链系统的记载为准。',
        '5. 暂停服务。您知悉基于区块链系统交易“不可撤销”的属性，我们不能为您暂停或撤销转账',
        '交易等操作，但在一定情况下，我们可以暂停或者限制某位用户对Bycoin软件的操作。',
        '6. 其他Super Node认为有必要提供的服务。',
        '用户接受Super Node提供的上述服务时应了解以下常见问题：',
        '1. 秉承着区块链的去中心化特点，并为了保护用户的数字资产安全，Super Node提供的是去中心化服务，大大区别于银行业金融机构。用户了解，Super Node不提供以下服务：',
        '（1）存储用户的钱包密码（即用户创建/导入钱包时设置的密码）、私钥、助记词、Keystore；',
        '（2）找回用户的钱包密码、私钥、助记词、Keystore；',
        '（3）冻结钱包；',
        '（4）挂失钱包；',
        '（5）交易回滚；',
        '（6）恢复钱包。',
        '2. 由于Super Node不提供上述服务，因此用户应当自行保管含有Bycoin的移动设备、备份Bycoin、备份钱包密码、助记词、私钥及Keystore。如用户遗失移动设备、删除且未备份Bycoin、删除且未备份钱包、钱包被盗或遗忘钱包密码、私钥、助记词、Keystore，Super Node均无法还原钱包或找回钱包密码、私钥、助记词、Keystore；如用户进行交易时误操作（例如输错转账地址），Super Node亦无法取消交易。',
        '3. Super Node和Bycoin所能够提供的数字资产管理服务并未包括所有已存在的数字资产，请勿通过Bycoin操作任何Bycoin不支持的数字资产。',
        '4. Bycoin仅是用户的数字资产管理工具，并非交易所或交易平台。虽然本协议将多次提及“交易”，其行为泛指用户使用Bycoin进行的转账和收款操作，这与交易所或交易平台上进行的“交易”有本质区别。',
        '四、 您的权利义务',
        '（一）创建或导入钱包',
        '1. 创建或导入钱包：您有权在您的移动设备上通过Bycoin创建和/或导入钱包，有权设定钱',
        '包的钱包密码等信息，并有权通过Bycoin应用程序，使用自己的钱包在区块链上进行转账和收款等交易。',
        '2. 身份验证：按照有关法律法规和政策要求，特定用户在使用Bycoin提供的有关服务时，应当按照Bycoin的提示及时完成相关身份验证，要求您提交包括但不限于您的姓名、身份证号码、手机号码、银行卡号信息等个人信息。否则该特定用户将无法使用有关服务，因特定用户拖延造成的损失由您自行承担。',
        '3. Super Node可能为不同的终端设备开发不同的软件版本，您应当根据实际需要选择下载合适的版本进行安装。如果您从未经合法授权的第三方获取本软件或与本软件名称相同的安装程序，Super Node将无法保证该软件能否正常使用，也无法保证其安全性，因此造成的损失由您自行承担。',
        '4. 本软件新版本发布后，旧版软件可能无法使用。Super Node不保证旧版软件的安全性、继续可用性及提供相应的客户服务。请您随时核对并下载最新版本。',
        '（二）使用',
        '1. 用户应自行妥善保管移动设备、钱包密码、私钥、助记词、Keystore等信息。Super Node不负责为用户保管以上信息。因您遗失移动设备、主动或被动泄露、遗忘钱包密码、私钥、助记词、Keystore或遭受他人攻击、诈骗等所引起的一切风险、责任、损失、费用应由您自行承担。',
        '2. 遵循信息提示。您了解并同意遵循Bycoin对您做出的信息提示，按照信息提示的内容进行操作，否则，由此引起的一切风险、责任、损失、费用等应由您自行承担。',
        '3. 您知悉并理解Bycoin没有义务对数字资产履行尽职调查义务，您应当理性做出投资决策并自主承担相应的投资风险。',
        '4. 积极完成身份验证。当Bycoin合理认为您的交易行为或交易情况出现异常的，或认为您的身份信息存在疑点的，或Bycoin认为应核对您身份证件或其他必要文件的情形时，请您积极配合Bycoin核对您的有效身份证件或其他必要文件，及时完成相关的身份验证。',
        '5. 转账。',
        '（1）您知悉对于Bycoin服务中您可使用的日计转账限额和笔数，可能因为您使用该转账服务时所处的国家/地区、监管要求、转账目的、Bycoin风险控制、身份验证等事由而不同。',
        '（2）您理解基于区块链操作的“不可撤销”属性，当您使用Bycoin转账功能时，您应当自行承担因您操作失误而导致的后果（包括但不限于因您输错转账地址、您自身选择转账节点服务器的问题）。',
        '（3）您知悉在使用Bycoin服务时，以下情况的出现可能导致转账“交易失败”或“打包超时”：',
        'a) 钱包余额不足；',
        'b) 交易矿工费不足；',
        'c) 区块链执行合约代码失败；',
        'd) 超出监管部门、Bycoin或法律法规规定的付款额度；',
        'e) 网络、设备等技术故障；',
        'f) 区块链网络拥堵、故障等原因引起交易被抛弃；',
        'g) 您的地址或交易对方地址被识别为特殊地址, 如高风险地址、交易所地址、ICO 地址、Token地址等。',
        '（4）您知悉Bycoin仅向您提供转账工具，在您使用Bycoin完成转账后，Super Node即完成了当次服务的所有义务，Super Node对其他纠纷争议，不负担任何义务。',
        '6. 合法合规。您知悉在Bycoin进行操作时或利用Bycoin上进行交易时，您应当遵循有关法律法规、国家政策的要求。',
        '7. 公告通知。Bycoin会以网站公告、电子邮件、发送短信、电话、消息中心信息、弹窗提示或客户端通知等方式向您发送通知，例如通知您交易进展情况，或者提示您进行相关操作，请您及时予以关注。',
        '8. 服务费用与纳税义务：',
        '（1）Bycoin暂时不向您收取任何形式的服务费或手续费，将来需对某些服务进行收费时将另行约定或公布规则；',
        '（2）您使用Bycoin进行转账时应支付矿工费，金额由您自行决定。矿工费由相关区块链系统收取；',
        '（3）您知悉在特定情况下，因为您所处的环境及网络状态不稳定，导致您的转账操作未完成时，亦会被相关区块链系统收取矿工费；',
        '（4）您因在Bycoin进行交易而发生的所有应纳税负及其它方面的费用均由您负责支付。',
        '五、 风险提示',
        '1. 您了解并知悉，由于数字资产领域的法律法规政策尚未健全，该领域的数字资产可能会产生无法兑现、技术不稳定等重大风险。且数字资产的价格波动幅度远高于其他金融资产。我们谨慎提醒您应当根据自身财务状况和风险偏好，理性选择持有或处置任何一种数字资产。Bycoin提供的行情查看功能仅系抓取部分交易所的数字资产汇率信息的搜索结果，并不表示为最新行情或最佳报价。',
        '2. 在使用Bycoin服务时，若您或您的相对方未遵从本协议或相关网站说明、交易、支付页面中之操作提示、规则，Bycoin并不保证交易会顺利完成，且Bycoin不承担损害赔偿责任。若发生前述情形，而款项已先行入账您的或您的交易方的Bycoin钱包或第三方钱包，您理解区块链操作具有的“不可逆”属性，以及相关交易具有“不可撤销”的特征，由您及您的相对方自行承担相应的风险后果。',
        '3. 您在交易过程中应当自行判断对方是否为完全民事行为能力人并自行决定是否与对方进行交易或转账给对方等，且您自行承担与此相关的所有风险。',
        '4. 在转账过程中，如果出现“交易失败”、“打包超时”等类似的异常信息提示时，您应通过相关区块链系统的官方途径或其他的区块链查询工具进行再次确认，以避免重复转账；否则，由此所引起的一切损失和费用应由您自行承担。',
        '5. 您理解当您在Bycoin上创建或导入钱包之后，您的Keystore、私钥、助记词等信息仅存储在当前的这台移动设备中，不存储在Bycoin或Super Node的服务器上。您可以按照Bycoin提供的操作指南采取同步钱包等方式更换移动设备。但若您未保存或备份钱包密码、私钥、助记词、Keystore等信息且在您移动设备丢失的情况下，您的数字资产将因此丢失，Super Node无法为您找回，您需自行承担相应损失。若您在导出、保存或备份钱包密码、私钥、助记词、Keystore等信息的时候泄密，或保存或备份上述信息的设备或服务器被黑客攻击或控制等情况下，您的数字资产将因此丢失，Super Node无法为您找回，您需自行承担相应损失。',
        '6. 我们建议您在创建或导入钱包时对您钱包的钱包密码、私钥、助记词及Keystore等信息做好安全备份。我们提请您注意，请不要采用以下备份方式：截图、邮件、记事本、短信、微信、QQ等电子备份方式。我们建议您在纸质记事本上抄写助记词和Keystore等信息，同时您亦可将电子数据保管至密码管理器。',
        '7. 我们建议您在安全的网络环境中使用Bycoin，确保您的移动设备没有越狱或Root， 以避免可能存在的安全隐患',
        '8. 请您在使用我们的服务过程中，警惕非Bycoin官方的诈骗行为。一旦发现此类行为，我们鼓励您第一时间告知我们。',
        '六、 服务的变更、中断、终止',
        '1. 您同意Super Node为保证自主业务经营权可以暂时提供部分服务功能，或于将来暂停部分服务功能或开通新的服务功能。当任何功能减少或者增加或者变化时，只要您仍然使用Super Node提供的服务，表示您仍然同意本协议或者本协议修正后的条款。',
        '2. 为保护您的数字资产安全，尽量避免您在不具备区块链基础知识的前提下使用Bycoin而产生的误操作或由此带来的风险，您必须先通过能力测评问卷并达到Super Node所要求的合格分数才能使用Bycoin服务，否则，Super Node有权限制或拒绝提供部分或全部的服务功能。',
        '3. 您理解存在如下情形时，Super Node将暂停提供服务：',
        '（1）因设备、区块链系统维修、升级、故障和通信中断等技术原因而中断业务；',
        '（2）因台风、地震、海啸、洪水、停电、战争或恐怖袭击等不可抗力因素，病毒、木马、黑客攻击、系统不稳定或政府行为等原因，造成Super Node系统不能提供服务或Super Node合理认为继续提供服务会有较大风险的；',
        '（3）发生Super Node无法控制或合理预见的其他情形。',
        '3. 当您出现如下情况时，Super Node可单方面中止或终止您使用Bycoin的部分或全部功能:',
        '（1）用户死亡；',
        '（2）盗用他人的钱包信息或移动设备；',
        '（3）填写个人信息时提供虚假信息、在回答能力测评问卷时非本人操作；',
        '（4）拒绝Super Node为提升Bycoin功能而发起的强制更新操作；',
        '（5）将Bycoin用于违法或犯罪活动；',
        '（6）妨碍其他用户正常使用；',
        '（7）伪称Super Node的工作人员或管理人员；',
        '（8）攻击、侵入、更改或以任何其他方式威胁Super Node计算机系统的正常运作；',
        '（9）利用Bycoin宣传垃圾广告；',
        '（10）散布谣言，损害Super Node和Bycoin商誉；',
        '（11）违法行为，其他违反本协议的行为，及Super Node合理认为应当暂停功能的情形。',
        '4. 当您与Super Node之间的服务关系变更、中断、终止时，您仍有权在合理时间内导出您钱包等信息。',
        '七、 您合法使用Super Node服务的承诺',
        '1. 您应遵守中华人民共和国相关法律法规及您所居住的国家或地区的法律法规，不得将Bycoin用于任何非法目的，也不得以任何非法方式使用Super Node服务。',
        '2. 您不得利用Bycoin从事违法或犯罪的行为，包括但不限于：',
        '（1）反对宪法所确定的基本原则，危害国家安全、泄漏国家秘密、颠覆国家政权、破坏国家统一的；',
        '（2）从事任何违法犯罪行为，包括但不限于洗钱、非法集资等；',
        '（3）通过使用任何自动化程序、软件、引擎、网络爬虫、网页分析工具、数据挖掘工具或类似工具，接入Super Node服务、收集或处理Super Node所提供的内容，干预或试图干预任何用户或任何其他方式接入Super Node服务的行为；',
        '（4）提供赌博资讯或以任何方式引诱他人参与赌博；',
        '（5）侵入他人Bycoin钱包盗取数字资产；',
        '（6）进行与交易对方宣称的交易内容不符的交易，或不真实的交易；',
        '（7）从事任何侵害或可能侵害Bycoin服务系统、数据之行为；',
        '（8）其他违法以及Super Node有正当理由认为不适当的行为。',
        '3. 您理解并同意，如因您违反有关法律（包括但不限于海关及税务方面的监管规定）或者本协议之规定，使Super Node遭受任何损失、受到任何第三方的索赔或任何行政管理部门的处罚，您应对Super Node进行赔偿，包括合理的律师费用。',
        '4. 您承诺按时缴纳Super Node的服务费用（如有），否则Super Node有权暂停或中止对您提供的服务。',
        '八、 隐私条款',
        '1. Super Node十分重视对用户隐私的保护，相关隐私保护政策请参考Super Node公布并不时更新的《Bycoin隐私政策》。',
        '九、 免责及责任限制',
        '1. Super Node仅对本协议中所列明的义务承担责任。',
        '2. 您理解和同意，在法律所允许的范围内，Super Node只能按照现有的技术水平和条件提供服务。因下列原因导致Bycoin无法正常提供服务，Super Node不承担责任：',
        '（1）Bycoin系统停机维护或升级；',
        '（2）因台风、地震、洪水、雷电或恐怖袭击等不可抗力原因；',
        '（3）您的移动设备软硬件和通信线路、供电线路出现故障的；',
        '（4）您操作不当或未通过Super Node授权或认可的方式使用Super Node服务的；',
        '（5）因病毒、木马、恶意程序攻击、网络拥堵、系统不稳定、系统或设备故障、通讯故障、电力故障、银行等原因或政府行为等原因；',
        '（6）非因Super Node的原因而引起的任何其它原因。',
        '3. Super Node对以下情形不承担责任：',
        '（1）因用户遗失移动设备、删除且未备份Bycoin、删除且未备份钱包、钱包被盗或遗忘钱包密码、私钥、助记词、Keystore而导致的数字资产丢失；',
        '（2）因用户自行泄露钱包密码、私钥、助记词、Keystore，或借用、转让或授权他人使用自己的移动设备或Bycoin钱包，或未通过Super Node官方渠道下载Bycoin应用程序或其他不安全的方式使用Bycoin应用程序导致的数字资产丢失；',
        '（3）因用户误操作（包括但不限于您输错转账地址、您自身选择转账节点服务器的问题）导致的数字资产丢失；',
        '（4）因时间滞后、区块链系统不稳定等原因导致Super Node拷贝用户在区块链上的交易记录发生偏差；',
        '（5）因用户不理解区块链技术的性质而进行误操作导致的数字资产丢失；',
        '4. 您理解Bycoin仅作为您数字资产管理的工具。',
        '5. Super Node可能同时为您及您的交易对手方提供服务，您同意对Super Node可能存在的该等行为予以明确豁免任何实际或潜在的利益冲突，并不得以此来主张Super Node在提供服务时存在法律上的瑕疵，也不因此而加重Super Node的责任或注意义务。',
        '6. Super Node不提供以下形式的保证：',
        '（1）Super Node从第三方交易所抓取的数字资产市场交易行情等信息的及时性、准确性、完整性、可靠性做出保证；',
        '（2）您经由Super Node服务取得的任何技术、产品、服务、资讯将符合您的期望；',
        '（3）Super Node服务将符合您的全部需求；',
        '（4）您在Bycoin上的交易各方会及时履行其在与您达成的交易协议中各项义务。',
        '7. 您理解Bycoin仅作为用户管理数字资产、显示交易信息的工具，Super Node不提供法律、税务或投资建议等服务。您应当自行向法律、税务、投资方面的专业人士寻求建议，且您在使用我们服务过程中所遭受的投资损失、数据损失等，Super Node概不负责。',
        '8.在任何情况下，Super Node对本协议所承担的违约赔偿责任总额不超过450BTM或人民币约500元，以较高的为准。',
        '9. 您理解根据有关中国政策法规的要求，我们可能不时更改我们的用户准入标准，限定向某一特定群体提供服务的范围和方式等。',
        '十、 完整协议',
        '1. 本协议由《Bycoin服务协议》、《Bycoin隐私政策》及Super Node不时公布的各项规则（包括“帮助中心”的内容）组成。',
        '2. 本协议的任何译文版本仅为方便用户而提供，无意对本协议的条款进行修改。如果本协议的中文版本与非中文版本之间存在冲突，应以中文版本为准。',
        '3.本协议部分内容被有管辖权的法院认定为违反或无效的，不因此影响其他内容的效力。',
        '十一、 知识产权保护',
        '1. Bycoin系Super Node开发并拥有知识产权的应用程序。 Bycoin中显示的任何内容（包括本协议、公告、文章、视频、音频、图片、档案、资讯、资料、商标或标识）的知识产权归Super Node或第三方权利人所有。用户仅可为持有和管理数字资产之目的使用Bycoin应用程序及其中的内容。未经Super Node或第三方权利人的事先书面同意，任何人不得擅自使用、修改、反向编译、复制、公开传播、改变、散布、发行或公开发表上述应用程序及内容。',
        '十二、 法律适用与争议解决',
        '1. 本协议及其修订版之效力、解释、变更、执行与争议解决均适用中华人民共和国法律，如无相关法律规定，则应当适用国际商业惯例和（或）行业惯例。',
        '2. 若您和Super Node之间发生任何纠纷或争议，首先应友好协商解决，协商不成的，任何一方可提交Super Node所在地有管辖权的法院管辖。',
        '十三、 其他',
        '1. 如您是中华人民共和国以外用户，您需全面了解并遵守您所在司法辖区与使用Super Node服务所有相关法律、法规及规则。',
        '2. 您在使用Super Node服务过程中，如遇到任何问题，您可以通过Bycoin提供的官方渠道联系我们。',
        '3. 您可以在Bycoin中查看本协议。Super Node鼓励您在每次访问Bycoin时都查阅Super Node的服务协议。',
        '4. 本协议自2018年11月1日起适用。',
        '本协议未尽事宜，您需遵守Super Node不时更新的公告及相关规则。',
        'Hangzhou Super Node Information Technology Co. Ltd.',
        '《Bycoin隐私政策》',
        '最近更新于：2018年11月12日',
        '尊敬的用户：',
        'Bytom Foundation Ltd.（以下简称“Super Node”或“我们”）尊重并保护用户（以下简称“您”或“用户”）的隐私，您使用Bycoin时，Super Node将按照本隐私政策（以下简称“本政策”）收集、使用您的个人信息。',
        'Super Node建议您在使用本产品（以下简称“Bycoin”）之前仔细阅读并理解本政策全部内容, 针对免责声明等条款在内的重要信息将以加粗的形式体现。本政策有关关键词定义与Super Node《Bycoin服务协议》保持一致。',
        '本政策可由Super Node在线随时更新，更新后的政策一旦公布即代替原来的政策，如果您不接受修改后的条款，请立即停止使用Bycoin，您继续使用Bycoin将被视为接受修改后的政策。经修改的政策一经在Bycoin上公布，立即自动生效。 您知悉本政策及其他有关规定适用于Bycoin。',
        '一、 我们收集您的哪些信息',
        '请您知悉，我们收集您的以下信息是出于满足您在Bycoin服务需要的目的，且我们十分重视对您隐私的保护。在我们收集您的信息时，将严格遵守“合法、正当、必要”的原则。且您知悉，若您不提供我们服务所需的相关信息，您在Bycoin的服务体验可能因此而受到影响。',
        '1. 我们将收集您的移动设备信息、操作记录、交易记录、钱包地址等个人信息。',
        '2. 为满足您的特定服务需求，我们将有可能收集您的姓名、银行卡号、手机号码、邮件地址等信息。',
        '3. 您知悉：您在Bycoin 上的钱包密码、私钥、助记词、Keystore并不存储或同步至Super Node服务器。Super Node不提供找回您的钱包密码、私钥、助记词、Keystore的服务。',
        '4. 除上述内容之外，您知悉在您使用Bycoin特定功能时，我们将在收集您的个人信息前向您作出特别提示，要求向您收集更多的个人信息。如您选择不同意，则视为您放弃使用Bycoin该特定功能。',
        '5. Bycoin不持有您的钱包私钥信息。',
        '6. 在法律法规允许的范围内，Super Node可能会在以下情形中收集并使用您的个人信息无需征得您的授权同意：',
        '（1） 与国家安全、国防安全有关的；',
        '（2） 与公共安全、公共卫生、重大公共利益有关的；',
        '（3） 与犯罪侦查、起诉、审判和判决执行等有关的；',
        '（4） 所收集的个人信息是您自行向社会公众公开的；',
        '（5） 从合法公开披露的信息中收集您的个人信息，如合法的新闻报道，政府信息公开等渠道；',
        '（6） 用于维护服务的安全和合规所必需的，例如发现、处理产品和服务的故障；',
        '（7） 法律法规规定的其他情形。',
        '7. 我们收集信息的方式如下：',
        '（1） 您向我们提供信息。例如，您在“个人中心”页面中填写姓名、手机号码或银行卡号，或在反馈问题时提供邮件地址，或在使用我们的特定服务时，您额外向我们提供。',
        '（2） 我们在您使用Bycoin的过程中获取信息，包括您移动设备信息以及您对Bycoin的操作记录等信息；',
        '（3） 我们通过区块链系统，拷贝您全部或部分的交易记录。但交易记录以区块链系统的记载为准。',
        '二、 我们如何使用您的信息',
        '1. 我们通过您移动设备的唯一序列号，确认您与您的钱包的对应关系。',
        '2. 我们将向您及时发送重要通知，如软件更新、服务协议及本政策条款的变更。',
        '3. 我们在Bycoin的“系统设置”中为您提供“指纹登录”选项，让您方便且更安全地管理您的数字资产。',
        '4. 我们通过收集您公开的钱包地址和提供的移动设备信息来处理您向我们提交的反馈。',
        '5. 我们收集您的个人信息进行Super Node内部审计、数据分析和研究等，以期不断提升我们的服务水平。',
        '6. 依照《Bycoin服务协议》及Super Node其他有关规定，Super Node将利用用户信息对用户的使用行为进行管理及处理。',
        '7. 法律法规规定及与监管机构配合的要求。',
        '三、 我们可能分享或传输您的信息',
        '1. Super Node在中华人民共和国境内收集和产生的用户个人信息将存储在中华人民共和国外的服务器上。若Super Node确需向境外传输您的个人信息，将在事前获得您的授权，且按照有关法律法规政策的要求进行跨境数据传输，并对您的个人信息履行保密义务。',
        '2. 未经您事先同意，Super Node不会将您的个人信息向任何第三方共享或转让，但以下情况除外：',
        '（1） 事先获得您明确的同意或授权；',
        '（2） 所收集的个人信息是您自行向社会公众公开的；',
        '（3） 所收集的个人信息系从合法公开披露的信息中收集，如合法的新闻报道，政府信息公开等渠道；',
        '（4） 与Super Node的关联方共享，我们只会共享必要的用户信息，且受本隐私条款中所声明的目的的约束；',
        '（5） 根据适用的法律法规、法律程序的要求、行政机关或司法机关的要求进行提供；',
        '（6） 在涉及合并、收购时，如涉及到个人信息转让，Super Node将要求个人信息接收方继续接受本政策的约束。',
        '四、 我们如何保护您的信息',
        '1. 如Super Node停止运营，Super Node将及时停止继续收集您个人信息的活动，将停止运营的通知公告在Bycoin上，并对所持有的您的个人信息在合理期限内进行删除或匿名化处理。',
        '2. 为了保护您的个人信息，Super Node将采取数据安全技术措施，提升内部合规水平，增加内部员工信息安全培训，并对相关数据设置安全访问权限等方式安全保护您的隐私信息。',
        '3. 我们将在Bycoin“消息中心”中向您发送有关信息安全的消息，并不时在Bycoin“帮助中心”版块更新钱包使用及信息保护的资料，供您参考。',
        '五、 对未成年人的保护',
        '我们对保护未满18周岁的未成年人做出如下特别约定：',
        '1. 未成年人应当在父母或监护人指导下使用Super Node相关服务。',
        '2. 我们建议未成年人的父母和监护人应当在阅读本政策、《Bycoin服务协议》及我们的其他有关规则的前提下，指导未成年人使用Bycoin。',
        '3. Bycoin将根据国家相关法律法规的规定保护未成年人的个人信息的保密性及安全性。',
        '六、 免责声明',
        '1. Super Node将在现有技术水平条件下尽可能采取合理的安全措施来保护您的个人信息，以避免信息的泄露、篡改或者毁损。Super Node系利用无线方式传输数据，因此，Super Node无法确保通过无线网络传输数据的隐私性和安全性。',
        '八、 其他',
        '1. 如您是中华人民共和国以外的用户，您需全面了解并遵守您所在司法辖区与使用Super Node服务所有相关法律、法规及规则。',
        '2. 您在使用Super Node服务过程中，如遇到任何有关个人信息使用的问题，您可以通过在Bycoin提交反馈等方式联系我们。',
        '3. 您可以在Bycoin中查看本政策及Super Node其他服务规则。我们鼓励您在每次访问Bycoin时都查阅Super Node的服务协议及隐私政策。',
        '4. 本政策的任何译文版本仅为方便用户而提供，无意对本政策的条款进行修改。如果本政策的中文版本与非中文版本之间存在冲突，应以中文版本为准。',
        '5. 本政策自2018年11月12日起适用。',
        '本政策未尽事宜，您需遵守Super Node不时更新的公告及相关规则。',
      ],
      en: [
        'Dear users:',
        'Thank you for choosing Bycoin service. Bycoin service agreement (hereinafter referred to as "this agreement") is signed by Hangzhou Super Node Information Technology Co. Ltd. (hereinafter referred to as "Super Node" or "we") and the user (hereinafter referred to as "you" or "user"). This agreement has the legal effect of the contract between you and Super Node.',
        'Super Node in this special remind you in the use of Bycoin (hereinafter referred to as "Bycoin" or "the software"), please read the "Bycoin service agreement" and later noted that the agreement, in particular the provisions of this agreement "liability and limitation of liability" and other terms will be reflected in the form of a bold, make sure you fully understand the terms of the provisions of this agreement, and independent considering risk.',
        'I. confirmation and acceptance of this agreement',
        '1. If you download the Bycoin software and create or import the wallet, you will be deemed to have fully read and accepted all the terms of this agreement. This agreement takes effect immediately and is binding on both parties.',
        '2. This agreement can be updated at any time by Super Node. Once the revised agreement is announced on Bycoin, it will take effect automatically without further notice. After Super Node publishes the terms of the modified agreement, if you do not accept the revised terms, please immediately stop using Bycoin. Your continued use of Bycoin will be deemed to accept the modified agreement.',
        '3. If you are under the age of 18, or have no or limited capacity for civil conduct, please use Bycoin under the guidance of your parents or guardians.',
        'Second, the definition of',
        '1. Bycoin: refers to the blockchain wallet developed by Super Node based on Bytom (and other public chains to be supported in the future), including other auxiliary tools developed to facilitate users to use blockchain system.',
        '2. User:',
        '(1) the user must be a natural person with full capacity for civil conduct;',
        '(2) if you use Bycoin service for minors under the age of 18, you need to use Bycoin under the guidance of your parents or guardians. If a person without capacity for civil conduct USES Bycoin or limits his capacity for civil conduct to conduct transactions beyond the scope of his civil rights or capacity, Bycoin shall have the right to hold you and your parents or guardian accountable for all the consequences caused.',
        '3. Creating or importing a wallet: means that you use Bycoin to confirm the fulfillment of this agreement and to create or import a wallet.',
        '4. Wallet password: during the process of creating Bycoin wallet, the software operation interface prompts you to fill in the password, which is used for encryption to protect the private key. As a decentralized application, the wallet password is not stored on your mobile device or the server of the Super Node, and once lost you need to reset the new password with the plaintext private key or mnemonic.',
        '5. Information prompt: the information prompt content involved in the operating interface of Bycoin software is recommended to users to follow the relevant steps.',
        '6. Specific user: refers to the user who must cooperate with Super Node to fulfill the personal information disclosure obligation in accordance with Chinese laws, regulations and policies.',
        '7. Private key: composed of 256-bit random characters, it is the core of the digital assets that the user owns and USES.',
        '8. Public key: the private key is generated through one-way derivation based on cryptography principle and used to generate the blockchain digital wallet address. The digital wallet address is the public deposit address.',
        '9. Mnemonic : they conform to the industry standard of blockchain BIP39 and consist of 12 (or 15/18/21/24) ordered words generated by random algorithm. It is a form of easy record of private key, convenient for users to backup and keep.',
        '10. Keystore: is a file form where the private key or mnemonic word is encrypted and saved through the wallet password set by the user. It is stored only on your mobile device and will not be synchronized to the Super Node server.',
        '11. Digital assets: refers to the types of digital assets that Bycoin currently supports, including but not limited to BTM.',
        '12. Personal information: refers to records in electronic or any other way to separate or combined with other information to identify the user personal identity of all kinds of information, including but not limited to natural person\'s name, date of birth, id number, personal biometric information, address, telephone number, bank card number, E-mail address, wallet, mobile devices, information, operation records, trading records, etc., but does not include a user\'s password wallet, private keys, mnemonic, Keystore.',
        'Iii. Service contents',
        '1.Create or import a wallet. For digital assets backed by Bycoin, you can use Bycoin to generate new wallets or compatible wallets generated by other wallet tools imported into the relevant blockchain system.',
        '2. Deposit and withdrawal. You can use Bycoin\'s deposit and withdrawal functions to manage digital assets. That is to say, you can use the private key for electronic signature and modify the account books of relevant blockchain. Transfer refers to that the payer USES the recipient\'s block chain address to transfer the asset, and the actual deposit and withdrawal behaviors all occur in the relevant blockchain system (instead of Bycoin).',
        '3. Manage digital assets. You can use Bycoin to add, store, and remove digital tokens supported by Bycoin (except BTM).',
        '4. Transaction records. We will copy all or part of your transaction records through the blockchain system. But transaction records are based on blockchain system records.',
        '5. Service suspension. You are aware of the "irrevocable" property of transactions based on the blockchain system. We cannot suspend or revoke transaction and other operations for you, but under certain circumstances, we can suspend or restrict the operation of Bycoin software by a certain user.',
        '6. Other services that Super Node deems necessary.',
        'Users should be aware of the following common problems when accepting the above services provided by Super Node:',
        '1. Adhering to the decentralization of blockchain and in order to protect the security of users\' digital assets, Super Node provides decentralized services, which is greatly different from banking financial institutions. Users understand that Super Node does not provide the following services:',
        '(1) store the user\'s wallet password (i.e. the password set by the user when creating/importing the wallet), private key, mnemonic word and Keystore;',
        '(2) retrieve the user\'s wallet password, private key, mnemonic word and Keystore;',
        '(3) frozen wallet;',
        '(4) report the loss of the wallet;',
        '(5) transaction rollback;',
        '(6) restore the wallet.',
        '2. Since Super Node does not provide the above services, users should keep mobile devices containing Bycoin, backup Bycoin, backup wallet password, mnemonic, private key and Keystore by themselves. If the user loses the mobile device, deletes and does not back up Bycoin, deletes and does not back up the wallet, the wallet is stolen or forgotten the wallet password, private key, mnemonic word, and Keystore, Super Node cannot restore or recover the wallet password, private key, mnemonic word, and Keystore. If a user makes a transaction by mistake (such as sending a wrong address), Super Node cannot cancel the transaction.',
        '3. The digital token management services provided by Super Node and Bycoin do not include all existing digital assets. Do not operate any digital token not supported by Bycoin through Bycoin.',
        '4. Bycoin is only a digital token management tool for users, not an exchange or trading platform. Although this agreement will refer to "transaction" several times, it generally refers to users\' deposit and withdrawal operations using Bycoin, which is fundamentally different from "transaction" on an exchange or trading platform.',
        'Iv. Your rights and obligations',
        'Create or import a wallet',
        '1. Create or import a wallet: you have the right to create and/or import a wallet via Bycoin on your mobile device, set the wallet password and other information, and use your own wallet to transfer and receive transactions on the blockchain through Bycoin app.',
        '2. Authentication: according to relevant laws, regulations and policies, when using the relevant services provided by Bycoin, specific users shall timely complete relevant authentication in accordance with Bycoin\'s prompts, requiring you to submit personal information including but not limited to your name, id number, mobile number, bank card number and so on. Otherwise, this particular user will not be able to use the service, and you will be responsible for the loss caused by the delay of this particular user.',
        '3. Super Node may be developing different versions of software for different end devices, and you should choose to download the appropriate version for installation based on actual needs. If you obtain the software or an installer with the same name of the software from an unauthorized third party, Super Node will not guarantee the normal use of the software or its security, and you shall bear the losses caused thereby.',
        '4. After the new version of the software is released, the old version of the software may not be available. Super Node does not guarantee the security, continued availability, or customer service of older software. Please check and download the latest version at any time.',
        '(2) use',
        '1. Users shall properly keep mobile devices, wallet passwords, private keys, mnemonic words, Keystore and other information. Super Node is not responsible for keeping the above information for the user. All risks, responsibilities, losses and expenses arising from the loss of your mobile device, active or passive disclosure, forgotten wallet password, private key, mnemonic word, Keystore or attack or fraud by others shall be borne by you.',
        'Follow information tips. You understand and agree to follow the information prompts made by Bycoin to you and operate according to the content of the information prompts. Otherwise, all risks, liabilities, losses and costs caused thereby shall be borne by you.',
        '3. You understand and understand that Bycoin has no obligation to perform due diligence on digital assets, and you should make investment decisions rationally and independently assume corresponding investment risks.',
        '4. Complete authentication actively. When Bycoin reasonably believes that your transaction behavior or transaction situation is abnormal, or that your identity information is questionable, or Bycoin thinks that your identity document or other necessary documents should be checked, please actively cooperate with Bycoin to check your valid identity document or other necessary documents and timely complete relevant authentication.',
        '5. Transfer.',
        '(1) you are aware that the daily account transfer limit and amount you can use in Bycoin service may be different for the country/region you are in when using the transfer service, regulatory requirements, transfer purpose, risk control of Bycoin, identity verification and other reasons.',
        '(2) you understand the "irrevocable" property based on the blockchain operation. When you use the Bycoin transfer function, you should bear the consequences caused by your operation error (including but not limited to the problem of your wrong transfer address and your own choice of transfer node server).',
        '(3) you are aware that when using Bycoin service, the following situations may lead to the transfer "transaction failure" or "package timeout" :',
        'A) insufficient wallet balance;',
        'B) the transaction gas is insufficient;',
        'C) blockchain fails to execute the contract code;',
        'D) exceeding the amount of payment required by regulatory authorities, Bycoin or laws and regulations;',
        'E) network, equipment, and other technical failures;',
        'F) transaction is abandoned due to blockchain network congestion, failure, and other reasons;',
        'G) your address or the address of the counterparty of the transaction is recognized as a special address, such as high-risk address, exchange address, ICO address, Token address, etc.',
        '(4) you know that Bycoin only provides you with the transfer tool. After you use Bycoin to complete the transfer, Super Node will complete all obligations of the service.',
        '6. Legal compliance. You know that you should comply with relevant laws, regulations and',
        'national policies when operating Bycoin or making transactions on Bycoin.',
        '7. Notice. Bycoin will send you notices by website announcement, email, sending SMS, phone, message center information, pop-up prompt or client notification, etc., such as informing you of the progress of the transaction or prompting you to perform relevant operations. Please pay attention to it in a timely manner.',
        '8. Service fees and tax obligations:',
        '(1) Bycoin will not charge you any service fee or service fee for the time being. The rules will be separately agreed or announced when charging for certain services in the future;',
        '(2) when you use Bycoin to transfer money, you should pay the gas . The amount is up to you. Gas is collected by the relevant blockchain system;',
        '(3) you are aware that under certain circumstances, if your transfer operation is not completed due to unstable environment and network status, the gas will be charged by the relevant blockchain system;',
        '(4) you shall be responsible for all taxes payable and other expenses incurred in connection with your transaction in Bycoin.',
        'Risk warning',
        '1. You understand and understand that, as the laws, regulations and policies in the field of digital tokens are not yet sound, the digital tokens in this field may generate significant risks such as uncashing and technical instability. And the price of digital tokens fluctuates much more than other financial assets. We caution that you should rationally choose to hold or dispose of any digital token according to your financial situation and risk preference. The ticker view feature provided by Bycoin is only a search result that captures the exchange rate information of digital tokens from some exchanges, and does not represent the latest quotation or the best offer.',
        '2. When using Bycoin service, if you or your counterpart fails to comply with this agreement or the operation tips and rules in the description, transaction and payment pages of relevant websites, Bycoin does not guarantee the fair to be completed smoothly, and Bycoin does not bear the liability for damages. If the foregoing happens and the payment has been entered',
        'into the account of your or your counterparty\'s Bycoin wallet or third-party wallet, you understand the "irreversible" property of the blockchain operation and the "irrevocable" feature of the relevant transaction，You and your counterpart shall bear the corresponding consequences at their own risk.',
        '3. You shall determine whether the other party is a person with full capacity for civil conduct and decide whether to transact with the other party or transfer money to the other party at your own risk.',
        '4. In the process of transfer, if "transaction failure", "package timeout" and other similar abnormal information prompts occur, you should reconfirm through the official channel of relevant blockchain system or other blockchain query tools to avoid repeated transfer; Otherwise, all losses and expenses arising therefrom shall be borne by you.',
        '5. You understand that after you create or import wallet on Bycoin, your Keystore, private key, mnemonic and other information are only stored in the current mobile device, not on the server of Bycoin or Super Node. You can replace mobile devices by synchronizing wallets and other means according to the operation guide provided by Bycoin. However, if you do not save or backup the wallet password, private key, mnemonic word, Keystore and other information, and if your mobile device is lost, your digital token will be lost, and Super Node cannot retrieve it for you, you shall bear the corresponding loss by yourself. If you export, save or backup the wallet password, private key, mnemonic word, Keystore and other information, or the device or server that saves or backs up the above information is attacked or controlled by hackers, your digital token will be lost, and Super Node cannot retrieve it for you, you shall bear the corresponding loss by yourself.',
        '6. We recommend that you make a safe backup of your wallet password, private key, mnemonic word, Keystore and other information when creating or importing your wallet. We draw your attention, please do not use the following backup: screenshot, email, notepad, SMS, WeChat, QQ and other electronic backup. We recommend that you copy mnemonic and Keystore information in a paper notepad. You can also store electronic data in the password manager.',
        '7. We suggest that you use Bycoin in a secure network environment to ensure that your mobile device does not jailbreak or Root to avoid potential security risks',
        '8. Please be aware of non-bycoin official fraud when using our service. We encourage you to inform us as soon as such behavior is discovered.',
        'Vi. Change, interruption and termination of the service',
        '1. You agree that Super Node may temporarily provide some service functions or suspend some service functions or open new service functions in the future to guarantee the independent business operation right. When any function is reduced or added or changed, as long as you still use the services provided by Super Node, you still agree to this agreement or the amended terms hereof.',
        '2. To protect your digital assets safe, try to avoid you don\'t have block chain under the premise of basic knowledge of using Bycoin wrong operation or the resulting risks, you must first achieve Super Node through ability assessment questionnaire and the required passing score can use Bycoin service, otherwise, Super Node reserves the right to limit or refused to provide part or all of the services.',
        '3. You understand that Super Node will suspend service when:',
        '(1) interruption of business due to technical reasons such as maintenance, upgrade, failure and communication interruption of equipment and blockchain system;',
        '(2) due to force majeure factors such as typhoon, earthquake, tsunami, flood, power failure, war or terrorist attack, virus, Trojan horse, hacker attack, system instability or government action, Super Node system cannot provide services or Super Node reasonably believes that there will be a greater risk of continuing to provide services;',
        '(3) other circumstances beyond Super Node\'s control or reasonably foreseeable occur.',
        '3. When the following situations occur to you, Super Node can unilaterally suspend or terminate some or all functions of Bycoin that you use:',
        '(1) user death;',
        '(2) stealing other people\'s wallet information or mobile devices;',
        '(3) providing false information when filling in personal information and not operating by myself when answering the competency assessment questionnaire;',
        '(4) reject the mandatory update operation initiated by Super Node to improve Bycoin function;',
        '(5) use Bycoin for illegal or criminal activities;',
        '(6) hindering the normal use of other users;',
        '(7) employees or managers falsely claiming to be Super Node;',
        '(8) attack, invade, alter or otherwise threaten the normal operation of the Super Node computer system;',
        '(9) use Bycoin to promote junk advertisements;',
        '(10) spread rumors to damage the goodwill of Super Node and Bycoin;',
        '(11) illegal ACTS, other ACTS in violation of this agreement, and circumstances in which Super Node reasonably believes that its functions should be suspended.',
        '4. When the service relationship between you and Super Node changes, breaks or terminates, you still have the right to export your wallet and other information within a reasonable time.',
        '7. Your legal commitment to use the Super Node service',
        '1. You shall abide by the relevant laws and regulations of the People\'s Republic of China and the laws and regulations of the country or region where you live. Bycoin shall not be used for any illegal purpose or in any illegal way to use Super Node services.',
        '2. You are not allowed to use Bycoin to engage in illegal or criminal activities, including but not limited to:',
        '(1) to oppose the basic principles set forth in the constitution, endanger national security,',
        'divulge state secrets, subvert state power or undermine national unity;',
        '(2) engage in any illegal and criminal ACTS, including but not limited to money laundering, illegal fund-raising, etc.;',
        '(3) by using any automated programs, software, engines, web crawlers, web analytics tools, data mining tools or similar tools to access the Super Node service, collect or process the content provided by Super Node, or attempt to interfere with any user\'s or any other access to the Super Node service;',
        '(4) provide gambling information or in any way induce others to participate in gambling;',
        '(5) hack into others\' Bycoin wallet to steal digital tokens;',
        '(6) conducting transactions inconsistent with the transactions claimed by the other party, or untrue transactions;',
        '(7) engage in any behavior that infringes or may infringe Bycoin service system and data;',
        '(8) other illegal ACTS and ACTS that Super Node may reasonably consider inappropriate.',
        '3. You understand and agree that if Super Node suffers any loss, claim from any third party or penalty imposed by any administrative authority due to your violation of relevant laws (including but not limited to customs and tax regulations) or provisions of this agreement, you shall indemnify Super Node, including reasonable attorney fees.',
        '4. You agree to pay the service fee of Super Node on time (if any), otherwise Super Node has the right to suspend or suspend the service provided to you.',
        'Viii. Privacy policy',
        '1. Super Node attaches great importance to the protection of users\' privacy. For relevant privacy protection policies, please refer to the Bycoin privacy policy published and updated from time to time by Super Node.',
        'Ix. Disclaimer and limitation of liability',
        '1. Super Node is only liable for the obligations set forth in this agreement.',
        '2. You understand and agree that, to the extent permitted by law, Super Node can only provide services in accordance with the existing technical level and conditions. As a result, Bycoin could not provide services normally for the following reasons, and Super Node was not responsible:',
        '(1) Bycoin system is down for maintenance or upgrade;',
        '(2) force majeure such as typhoon, earthquake, flood, lightning or terrorist attack;',
        '(3) failure of your mobile device\'s hardware and software, communication lines and power supply lines;',
        '(4) you use the services of Super Node improperly or without authorization or approval of Super Node;',
        '(5) due to viruses, Trojan horses, malicious program attacks, network congestion, system instability, system or equipment failure, communication failure, power failure, Banks and other reasons or government actions;',
        '(6) any other reason not caused by Super Node.',
        '3. Super Node is not liable for:',
        '(1) loss of digital tokens caused by users\' loss of mobile devices, deletion and failure to back up Bycoin, deletion and failure to back up wallet, wallet theft or forgetting wallet password, private key, mnemonic word and Keystore;',
        '(2) loss of digital tokens caused by users\' disclosure of wallet password, private key, mnemonic word and Keystore, or borrowing, transferring or authorizing others to use their mobile',
        'devices or Bycoin wallet, or not downloading Bycoin application through Super Node official channel or using Bycoin application in other unsafe ways;',
        '(3) loss of digital assets caused by user\'s wrong operation (including but not limited to the wrong transfer address you input and the server of transfer node you choose);',
        '(4) due to time delay, instability of blockchain system and other reasons, transaction records of Super Node copy users on blockchain are deviated;',
        '(5) loss of digital assets due to misoperation by users who do not understand the nature of blockchain technology;',
        '(6) risks and consequences arising from users\' operation.',
        '4. Super Node may provide services to you and your counterparty at the same time. You agree to expressly exempt Super Node from any actual or potential conflict of interest which may exist in such actions, and shall not claim that there are legal defects in the provision of services by Super Node, nor thereby increase the liability or duty of care of Super Node.',
        '5. Super Node does not provide the following forms of warranty:',
        '(1) the timeliness, accuracy, integrity and reliability of the information captured by Super Node in the digital asset market from third-party exchanges are guaranteed;',
        '(2) any technology, products, services and information you obtain through the Super Node',
        'service will meet your expectations;',
        '(3) the Super Node service will meet all your needs;',
        '(4) all parties to your transaction on Bycoin will timely fulfill their obligations in the transaction agreement reached with you.',
        '6. You understand that Bycoin only serves as a tool for users to manage digital assets and display transaction information. Super Node does not provide legal, tax or investment advice and other services. You should seek advice from legal, tax and investment professionals on your own, and Super Node shall not be responsible for any investment loss or data loss suffered by you during the use of our services.',
        '7. In any event, the total liability of Super Node for breach of this agreement shall not exceed 450BTM or RMB 500 yuan, whichever is higher.',
        '8. You understand that in accordance with the requirements of relevant Chinese policies and regulations, we may change our user access criteria from time to time to limit the scope and mode of providing services to a particular group.',
        'X. entire agreement',
        '1. This agreement is made up of Bycoin service agreement, Bycoin privacy policy and rules published by Super Node from time to time (including contents of "help center").',
        '2. Any translated version of this agreement is provided for the convenience of users only, and there is no intention to modify the terms of this agreement. If there is a conflict between the Chinese version and the non-chinese version of this agreement, the Chinese version shall prevail.',
        '3. Part of this agreement shall not affect the validity of other contents if it is deemed to be violated or invalid by a court with jurisdiction.',
        'Xi. Protection of intellectual property rights',
        '1. Bycoin is an application developed and owned by Super Node with intellectual property rights. The intellectual property rights of any content (including this agreement, announcement, article, video, audio, picture, file, information, data, trademark or logo) displayed in Bycoin belong to Super Node or a third party right holder. Users can only use Bycoin applications and their contents for the purpose of holding and managing digital tokens. Without the prior written consent of Super Node or any third party right holder, no person shall use, modify, reverse compile, copy, publicly disseminate, change, distribute, distribute or publicly publish the above applications and contents.',
        'Application of law and dispute resolution',
        '1. The validity, interpretation, modification, implementation and dispute resolution of this agreement and its revised version shall be governed by the laws of the People\'s Republic of China. In the absence of relevant provisions of laws, international commercial practices and/or industrial practices shall apply.',
        '2. If any dispute or dispute arises between you and Super Node, it shall be settled through friendly negotiation. If no agreement can be reached through negotiation, either party may submit the dispute to the competent court in the place where Super Node is located.',
        'Xiii. Miscellaneous',
        '1. If you are a user outside the People\'s Republic of China, you need to fully understand and comply with all relevant laws, regulations and rules of your jurisdiction and use of Super Node service.',
        '2. In the process of using Super Node service, if you encounter any problems, you can contact us through the official channel provided by Bycoin.',
        '3. You can view this agreement in Bycoin. Super Node encourages you to consult the service agreement of Super Node every time you visit Bycoin.',
        '4. This agreement shall be effective as of November 1, 2018.',
        'For matters not covered in this agreement, you shall abide by the notice and relevant rules updated by Super Node from time to time.',
        'Hangzhou Super Node Information Technology Co. Ltd.',
        'Bycoin privacy policy',
        'Last updated on: November 12, 2018',
        'Dear users,',
        'Bytom Foundation Ltd. (hereinafter referred to as "Super Node" or "we") respects and protects the privacy of users (hereinafter referred to as "you" or "user"). When you use Bycoin, Super Node will collect and use your personal information in accordance with this privacy policy (hereinafter referred to as "this policy").',
        'Super Node suggests that you carefully read and understand all contents of this policy before using this product (hereinafter referred to as "Bycoin"). Important information including disclaimer and other terms will be shown in bold. The definition of key words in this policy is consistent with Super Node\'s Bycoin service agreement.',
        'This policy can be updated by Super Node online at any time. Once the updated policy is published, it will replace the original policy. If you do not accept the revised terms, please immediately stop using Bycoin, and your continued use of Bycoin will be deemed as acceptance of the revised policy. The revised policy will automatically take effect as soon as it is published on Bycoin. You know that this policy and other relevant provisions are applicable to Bycoin independently owned by Super Node on Bycoin.',
        'I. what information do we collect about you',
        'Please note that we collect the following information of you for the purpose of meeting your needs in Bycoin service, and we attach great importance to the protection of your privacy. When we collect your information, we will strictly abide by the principle of "legal, legitimate and necessary". Moreover, you know that your service experience in Bycoin may be affected if you do not provide relevant information required by our service.',
        '1. We will collect your mobile device information, operation records, transaction records, wallet address and other personal information.',
        '2. To meet your specific service requirements, we will collect your name, bank card number,',
        'mobile phone number, email address and other information.',
        '3. You are aware that your wallet password, private key, mnemonic word and Keystore on Bycoin do not store or synchronize to Super Node server. Super Node does not provide services to retrieve your wallet password, private key, mnemonic, Keystore.',
        '4. In addition to the above content, you know that when you use the specific function of Bycoin, we will make a special reminder to you before collecting your personal information and ask for more personal information from you. If you choose not to agree, it is deemed that you give up the use of Bycoin, the specific function.',
        '5. To the extent permitted by laws and regulations, Super Node may collect and use your personal information in the following situations without your authorization and consent:',
        '(1) those related to national security and national defense security;',
        '(2) those related to public security, public health or major public interests;',
        '(3) relating to criminal investigation, prosecution, trial and execution of judgment;',
        '(4) the personal information collected is disclosed to the public by you;',
        '(5) collect your personal information from legally disclosed information, such as legal news reports, government information disclosure and other channels;',
        '(6) it is necessary to maintain the safety and compliance of the services, such as finding and handling the faults of the products and services;',
        '(7) other circumstances stipulated by laws and regulations.',
        '6. We collect information as follows:',
        '(1) you provide us with information. For example, you fill in your name, mobile phone number or bank card number in the "personal center" page, or provide an email address when giving feedback to questions, or provide additional information to us when using our specific services.',
        '(2) we obtain information during your use of Bycoin, including your mobile device information and your operation record of Bycoin;',
        '(3) we copy all or part of your transaction records through the blockchain system. However, the transaction records shall be subject to the records of the block chain system.',
        'How do we use your information',
        '1. We confirm the correspondence between you and your wallet through the unique serial number of your mobile device.',
        '2. We will timely send you important notices, such as software updates, service agreements and changes to the terms of this policy.',
        '3. We provide "fingerprint login" option for you in the "system Settings" of Bycoin, which makes it convenient and more secure for you to manage your digital assets.',
        '4. We process your feedback to us by collecting your public wallet address and mobile device information.',
        '5. We collect your personal information for internal audit, data analysis and research in Super Node, so as to continuously improve our service level.',
        '6. In accordance with Bycoin service agreement and other relevant regulations of Super Node, Super Node will manage and process users\' usage behavior by using user information.',
        '7. Requirements of laws and regulations and cooperation with regulatory agencies.',
        'We may share or transmit your information',
        '1. Personal information collected and generated by Super Node within the People\'s Republic of China will be stored on servers outside the People\'s Republic of China. If Super Node really needs to transfer your personal information overseas, it will obtain your authorization in advance, transmits data across the border in accordance with relevant laws, regulations and policies, and keeps your personal information confidential.',
        '2. Without your prior consent, Super Node will not share or transfer your personal information to any third party, except as follows:',
        '(1) obtain your express consent or authorization in advance;',
        '(2) the personal information collected is disclosed to the public by you;',
        '(3) the personal information collected is collected from the information legally disclosed, such as legal news reports, government information disclosure and other channels;',
        '(4) sharing with related parties of Super Node, we will only share necessary user information and are bound by the purpose stated in this privacy clause;',
        '(5) according to applicable laws and regulations, requirements of legal procedures, and requirements of administrative or judicial organs;',
        '(6) in case of merger or acquisition, if personal information transfer is involved, Super Node will require the recipient of personal information to continue to be bound by this policy.',
        'How do we protect your information',
        '1. If Super Node ceases to operate, Super Node will stop the activity of collecting your personal information in a timely manner, notice of cessation of operation will be announced on Bycoin, and your personal information held by Super Node will be deleted or anonymous within a reasonable period of time.',
        '2. In order to protect your personal information, Super Node will take data security technical measures, improve internal compliance level, increase internal employee information security training, and set security access rights for relevant data to protect your privacy information.',
        '3. We will send you information about information security in Bycoin "message center", and update wallet usage and information protection information in Bycoin "help center" section from time to time for your reference.',
        'Protection of minors',
        'We hereby make the following special provisions for the protection of minors under the age of 18:',
        '1. Minors should use Super Node related services under the guidance of their parents or guardians.',
        '2. We suggest that parents and guardians of minors should guide minors to use Bycoin on the premise of reading this policy, Bycoin service agreement and our other relevant rules.',
        '3. Bycoin will protect the confidentiality and security of minors\' personal information in accordance with relevant national laws and regulations.',
        'Vii. Disclaimer',
        '1. Super Node will take reasonable security measures to protect your personal information as far as possible under current technical conditions to avoid information leakage, tampering or damage. The Super Node system USES wireless data transmission, so the privacy and security of data transmission over wireless networks cannot be guaranteed.',
        'Eight, other',
        '1. If you are a user outside the People\'s Republic of China, you need to fully understand and comply with all relevant laws, regulations and rules of your jurisdiction and the use of Super Node service.',
        '2. In the process of using Super Node service, if you encounter any questions about the use of personal information, you can contact us by submitting feedback in Bycoin and other ways.',
        '3. You can view this policy and other service rules of Super Node in Bycoin. We encourage you to check the service agreement and privacy policy of Super Node every time you visit Bycoin.',
        '4. Any translated version of this policy is provided for the convenience of users only, and there is no intention to modify the provisions of this policy. If there is a conflict between the Chinese version of this policy and the non-chinese version, the Chinese version shall prevail.',
        '5. This policy shall apply from November 12, 2018.',
        'For matters not covered in this policy, you are required to comply with the notice and relevant rules updated by Super Node from time to time.',
      ]
    };

    return (
      <div title={lang === 'zh' ? 'Bycoin 服务协议' : 'Bycoin Service Agreement'}>
        <SEO
          title="Bycoin Service Agreement" 
        />
        <Wrap>
          {
            agreement[lang].map((item, index) => (
              <Paragraph key={index}>{item}</Paragraph>
            ))
          }
        </Wrap>
      </div>
    )
  }
}
